version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.11.0

      steps:
        - checkout

        - run:
            name: "What Branch Am I On?"
            command: |
              echo $CIRCLE_BRANCH
        - run:
            name: "Will this work?"
            command: |
              echo ${CIRCLE_BRANCH}
        -restore_cache:
          keys:
            - deps-v1--{{ checksum my-medusa-starter/package-lock.json}}
            - deps-v1--

        - run:
            name: "Build storefront deps"
            command: |
              cd my-medusa-starter &&
              npm i

      - save_cache:
          paths:
            - my-medusa-starter/node_modules
          keys: deps-v1--{{ checksum my-medusa-starter/package-lock.json}}

workflows:
  build-storefront:
    jobs:
      - build-assets:
          context: Staging
    filter:
      branches:
        only:
          - circle-branch

